version: '2'

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
    - 2181:2181
    environment:
      ZOO_MY_ID: 1
  kafka1:
    image: wurstmeister/kafka
    links:
    - zoo1:zk
    ports:
    - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - zoo1